In [3]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [7]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

In [15]:
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([[-2,-2]])
nbrs = NearestNeighbors(n_neighbors=1, algorithm='ball_tree').fit(X)
distances, indices = nbrs.kneighbors(Y)

In [16]:
indices

array([[1]])

In [17]:
distances

array([[1.]])

In [13]:
print X

[[-1 -1]
 [-2 -1]
 [-3 -2]
 [ 1  1]
 [ 2  1]
 [ 3  2]]


In [24]:
x = np.random.rand(10000,3)
y = np.random.rand(10,3)

nbrs = NearestNeighbors(n_neighbors=1, algorithm='ball_tree').fit(x)
distances, indices = nbrs.kneighbors(y)

distances

array([[0.03566347],
       [0.00992722],
       [0.04279469],
       [0.04463704],
       [0.02522673],
       [0.0178423 ],
       [0.02420743],
       [0.02892726],
       [0.04910488],
       [0.02149902]])

In [25]:
indices

array([[7498],
       [1710],
       [ 619],
       [8429],
       [6922],
       [3846],
       [1508],
       [5137],
       [4619],
       [9366]])

In [33]:
a = np.array([1, 2, 6, 4, 2, 3, 2])
u, inverse = np.unique(a, return_inverse=True) 
print u
print inverse

[1 2 3 4 6]
[0 1 4 3 1 2 1]
